### ISSUE TITLE
How to realize the SWAP gate in the front end version?

### ISSUE THREAD

**Issue by ElonDormancy** [Santics/UQCS#1]
Because we use the if(else) to decide the whether controlling,we are not able to explicitly construct two qubit gate unless control gate. We need a new method to apply the two qubit gate. @ElonDormancy

**Comment by Santics** [comment]
Swapping two qubits means that there are four wavefunction coefficients in each group, two of which need not to be changed(00,11),so we just find sequence numbers(in the wavefunction array) of two coefficients needing to be changed(01,10) in each group and exchange the correspongding coefficients.If we had done the procedure for every group, we should have succeed. 

The only problem is four elements in each group may not always be next to each other. To solve this ,we define a parameter named BaseIndice which locates the first element( 00 ) in each group, and then we define another parameter named Indice to locate all elements( 00, 01 ,10 ,11 ) in each group. It is easy to get Indice( 0 ,  2**(qubitA) , 2**(qubitB) , 2**(qubitA)+2**(qubitB)).


To get BaseIndice , we need a binary operation ( binary & ).Here is the  fundamental algorithm.
```
//indice is a vector to store calculated baseindice
//targetSequence is an array indicting qubit position
//for example  7:1, 6:0 , 4:0 , 2:1, 1:0, 0:1 (attention qubits 5 and 3 are not included if we want to SWAP them )
//dim is the qubit size(how many qubits in targetSequence), in our process to implement SWAP gate ,it is (totalQubitSize -2), 
//which means there are 2**(totalQubitSize -2) BaseIndice numbers

void Gate::indiceBinaryGenerator(vector<int>& baseindice, vector<int>& targetSequence, int dim)
{
	int i = 0, j = 0, k = 0;
	for (i = 0; i < pow(2, dim); i++)
	{
		baseindice[i] = 0;
               // j == j << 1 is binary shift operation which can be replaced with j *= 2
               //loop parameter k indicates we intend to traverse every qubit in targetSequence
		for (j = 1, k = 0; k < dim; j = j << 1, k++)
		{
                       // attention: not && but &(binary & operation)
                       //this step is to check  whether corresponding qubits is 1
                       //if it is 1, we add 2**(thisqubitorder) to BaseIndice[i]
			if (i & j)
			{
				indice[i] += pow(2, targetSequence[k]);
			}
		}
	}
	return;
}
```
